Repository googleapis/java-datastream, pull requests merged in 2021-09, with the labels that each got.

#56 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: datastream

#68 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: datastream

#60 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: datastream
